goog.provide('bg.Location');

goog.require('lime.Sprite');

bg.Location = function(locData) {
    lime.Sprite.call(this);

    this.setSize(locData['sizeX'], locData['sizeY']);
    this.setAnchorPoint(locData['anchorX'], locData['anchorY']);
    this.setPosition(locData['positionX'], locData['positionY']);
    this.setFill(locData['fillColor']);

    this.name = locData['name'];
    this.blackMove = locData['blackMove'];
    this.whiteMove = locData['whiteMove'];
    this.clueCount = locData['clueCount'];
    this.adjacent = locData['adjacent'];
    this.gate = undefined;

    this.qualityRenderer = true;

};
goog.inherits(bg.Location, lime.Sprite);

var locMap = {
    '001': {
              'name': 'Newspaper',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 0,
              'positionY': 0,
              'fillColor': '#295081',
              'adjacent': {
                            'Northside':1,
                          },
              'blackMove': 'Northside',
              'whiteMove': 'Northside',
            },
    '002': {
              'name': 'Train Station',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 91,
              'positionY': 0,
              'fillColor': '#295081',
              'adjacent': {
                            'Northside':1,
                          },
              'blackMove': 'Northside',
              'whiteMove': 'Northside',
            },
    '003': {
              'name': 'Bank of Arkham',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 181,
              'positionY': 0,
              'fillColor': '#295081',
              'adjacent': {
                            'Downtown':1,
                          },
              'blackMove': 'Downtown',
              'whiteMove': 'Downtown',
            },
    '004': {
              'name': 'Arkham Asylum',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 271,
              'positionY': 0,
              'fillColor': '#295081',
              'adjacent': {
                            'Downtown':1,
                          },
              'blackMove': 'Downtown',
              'whiteMove': 'Downtown',
            },
    '005': {
              'name': 'Curiositie Shoppe',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 0,
              'positionY': 91,
              'fillColor': '#295081',
              'adjacent': {
                            'Northside':1,
                          },
              'blackMove': 'Northside',
              'whiteMove': 'Northside',
            },
    '006': {
              'name': 'Northside',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 91,
              'positionY': 91,
              'fillColor': '#295081',
              'adjacent': {
                            'Newspaper':1,
                            'Train Station':1,
                            'Curiositie Shoppe':1,
                            'Downtown':1,
                            'Merchant District':1,
                          },
              'blackMove': 'Merchant District',
              'whiteMove': 'Downtown',
            },
    '007': {
              'name': 'Downtown',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 181,
              'positionY': 91,
              'fillColor': '#295081',
              'adjacent': {
                            'Arkham Asylum':1,
                            'Bank of Arkham':1,
                            'Northside':1,
                            'Independence Square':1,
                            'Easttown':1,
                          },
              'blackMove': 'Northside',
              'whiteMove': 'Easttown',
            },
    '008': {
              'name': 'Independence Square',
              'clueCount': 1,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 271,
              'positionY': 91,
              'fillColor': '#295081',
              'adjacent': {
                            'Downtown':1,
                          },
              'blackMove': 'Downtown',
              'whiteMove': 'Downtown',
            },
    '009': {
              'name': 'Hibb\'s Roadhouse',
              'clueCount': 1,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 271,
              'positionY': 181,
              'fillColor': '#295081',
              'adjacent': {
                            'Easttown':1,
                          },
              'blackMove': 'Easttown',
              'whiteMove': 'Easttown',
            },
    '010': {
              'name': 'Easttown',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 181,
              'positionY': 271,
              'fillColor': '#295081',
              'adjacent': {
                            'Downtown':1,
                            'Hibb\'s Roadhouse':1,
                            'Velma\'s Diner':1,
                            'Police Station':1,
                            'Rivertown':1,
                          },
              'blackMove': 'Downtown',
              'whiteMove': 'Rivertown',
            },
    '011': {
              'name': 'Velma\'s Diner',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 271,
              'positionY': 271,
              'fillColor': '#295081',
              'adjacent': {
                            'Easttown':1,
                          },
              'blackMove': 'Easttown',
              'whiteMove': 'Easttown',
            },
    '012': {
              'name': 'Police Station',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 271,
              'positionY': 361,
              'fillColor': '#295081',
              'adjacent': {
                            'Easttown':1,
                          },
              'blackMove': 'Easttown',
              'whiteMove': 'Easttown',
            },
    '013': {
              'name': 'Unvisited Isle',
              'clueCount': 1,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 0,
              'positionY': 451,
              'fillColor': '#295081',
              'adjacent': {
                            'Merchant District':1,
                          },
              'blackMove': 'Merchant District',
              'whiteMove': 'Merchant District',
            },
    '014': {
              'name': 'River Docks',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 0,
              'positionY': 541,
              'fillColor': '#295081',
              'adjacent': {
                            'Merchant District':1,
                          },
              'blackMove': 'Merchant District',
              'whiteMove': 'Merchant District',
            },
    '015': {
              'name': 'Merchant District',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 91,
              'positionY': 541,
              'fillColor': '#295081',
              'adjacent': {
                            'Northside':1,
                            'Downtown':1,
                            'Rivertown':1,
                            'Miskatonic University':1,
                            'Unvisited Isle':1,
                            'River Docks':1,
                            'The Unnamable':1,
                          },
              'blackMove': 'Miskatonic University',
              'whiteMove': 'Northside',
            },
    '016': {
              'name': 'The Unnamable',
              'clueCount': 1,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 0,
              'positionY': 631,
              'fillColor': '#295081',
              'adjacent': {
                            'Merchant District':1,
                          },
              'blackMove': 'Merchant District',
              'whiteMove': 'Merchant District',
            },
    '017': {
              'name': 'Graveyard',
              'clueCount': 1,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 271,
              'positionY': 451,
              'fillColor': '#295081',
              'adjacent': {
                            'Rivertown':1,
                          },
              'blackMove': 'Rivertown',
              'whiteMove': 'Rivertown',
            },
    '018': {
              'name': 'Rivertown',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 181,
              'positionY': 541,
              'fillColor': '#295081',
              'adjacent': {
                            'Graveyard':1,
                            'Black Cave':1,
                            'General Store':1,
                            'Easttown':1,
                            'Merchant District':1,
                            'French Hill':1,
                          },
              'blackMove': 'Easttown',
              'whiteMove': 'French Hill',
            },
    '019': {
              'name': 'Black Cave',
              'clueCount': 1,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 271,
              'positionY': 541,
              'fillColor': '#295081',
              'adjacent': {
                            'Rivertown':1,
                          },
              'blackMove': 'Rivertown',
              'whiteMove': 'Rivertown',
            },
    '020': {
              'name': 'General Store',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 271,
              'positionY': 631,
              'fillColor': '#295081',
              'adjacent': {
                            'Rivertown':1,
                          },
              'blackMove': 'Rivertown',
              'whiteMove': 'Rivertown',
            },
    '021': {
              'name': 'Science Building',
              'clueCount': 1,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 0,
              'positionY': 721,
              'fillColor': '#295081',
              'adjacent': {
                            'Miskatonic University':1,
                          },
              'blackMove': 'Miskatonic University',
              'whiteMove': 'Miskatonic University',
            },
    '022': {
              'name': 'Administration',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 0,
              'positionY': 811,
              'fillColor': '#295081',
              'adjacent': {
                            'Miskatonic University':1,
                          },
              'blackMove': 'Miskatonic University',
              'whiteMove': 'Miskatonic University',
            },
    '023': {
              'name': 'Miskatonic University',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 91,
              'positionY': 811,
              'fillColor': '#295081',
              'adjacent': {
                            'Science Building':1,
                            'Administration':1,
                            'Library':1,
                            'Merchant District':1,
                            'French Hill':1,
                            'Uptown':1,
                          },
              'blackMove': 'Uptown',
              'whiteMove': 'Merchant District',
            },
    '024': {
              'name': 'Library',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 0,
              'positionY': 901,
              'fillColor': '#295081',
              'adjacent': {
                            'Miskatonic University':1,
                          },
              'blackMove': 'Miskatonic University',
              'whiteMove': 'Miskatonic University',
            },
    '025': {
              'name': 'French Hill',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 181,
              'positionY': 811,
              'fillColor': '#295081',
              'adjacent': {
                            'The Witch House':1,
                            'Silver Twilight Lodge':1,
                            'Rivertown':1,
                            'Southside':1,
                            'Miskatonic University':1,
                          },
              'blackMove': 'Rivertown',
              'whiteMove': 'Southside',
            },
    '026': {
              'name': 'The Witch House',
              'clueCount': 1,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 271,
              'positionY': 811,
              'fillColor': '#295081',
              'adjacent': {
                            'French Hill':1,
                          },
              'blackMove': 'French Hill',
              'whiteMove': 'French Hill',
            },
    '027': {
              'name': 'Silver Twilight Lodge',
              'clueCount': 1,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 271,
              'positionY': 901,
              'fillColor': '#295081',
              'adjacent': {
                            'French Hill':1,
                          },
              'blackMove': 'French Hill',
              'whiteMove': 'French Hill',
            },
    '028': {
              'name': 'St. Mary\'s Hospital',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 0,
              'positionY': 991,
              'fillColor': '#295081',
              'adjacent': {
                            'Uptown':1,
                          },
              'blackMove': 'Uptown',
              'whiteMove': 'Uptown',
            },
    '029': {
              'name': 'Uptown',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 91,
              'positionY': 991,
              'fillColor': '#295081',
              'adjacent': {
                            'St. Mary\'s Hospital':1,
                            'Southside':1,
                            'Miskatonic University':1,
                            'Ye Olde Magick Shoppe':1,
                            'Woods':1,

                          },
              'blackMove': 'Southside',
              'whiteMove': 'Miskatonic University',
            },
    '030': {
              'name': 'Southside',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 181,
              'positionY': 991,
              'fillColor': '#295081',
              'adjacent': {
                            'Uptown':1,
                            'French Hill':1,
                            'Ma\'s Boarding House':1,
                            'Historical Society':1,
                            'South Church':1,
                          },
              'blackMove': 'French Hill',
              'whiteMove': 'Uptown',
            },
    '031': {
              'name': 'Ma\'s Boarding House',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 271,
              'positionY': 991,
              'fillColor': '#295081',
              'adjacent': {
                            'Southside':1,
                          },
              'blackMove': 'Southside',
              'whiteMove': 'Southside',
            },
    '032': {
              'name': 'Ye Olde Magick Shoppe',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 0,
              'positionY': 1081,
              'fillColor': '#295081',
              'adjacent': {
                            'Uptown':1,
                          },
              'blackMove': 'Uptown',
              'whiteMove': 'Uptown',
            },
    '033': {
              'name': 'Woods',
              'clueCount': 1,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 91,
              'positionY': 1081,
              'fillColor': '#295081',
              'adjacent': {
                            'Uptown':1,
                          },
              'blackMove': 'Uptown',
              'whiteMove': 'Uptown',
            },
    '034': {
              'name': 'Historical Society',
              'clueCount': 1,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 181,
              'positionY': 1081,
              'fillColor': '#295081',
              'adjacent': {
                            'Southside':1,
                          },
              'blackMove': 'Southside',
              'whiteMove': 'Southside',
            },
    '035': {
              'name': 'South Church',
              'clueCount': 0,
              'anchorX': 0,
              'anchorY': 0,
              'sizeX': 90,
              'sizeY': 90,
              'positionX': 271,
              'positionY': 1081,
              'fillColor': '#295081',
              'adjacent': {
                            'Southside':1,
                          },
              'blackMove': 'Southside',
              'whiteMove': 'Southside',
            },
};
